Alinto/sope

sope-mime/NGImap4/NGImap4Connection.m
This will prevent a `too long request` error when you have big folders (~ 5k uids). With this fetchUids will fetch uids in 1k batches.
=> NGImap4Connection:fetchUids retrieve uids in batches

sope-core/NGStreams/NGCTextStream.m
By computing the maximum length and then using `strlen()` we were being
efficient, but if there was a `\0` in the command (e.g. when there is an
attachment in a message and its data has that byte), `strlen()` skipped
the rest of the string and returned a smaller length.
Suggested `NEWS` line:
* `Avoid server freeze due to attached files`
=> Compute the exact string length for IMAP commands

sope-appserver/NGObjWeb/WOWatchDogApplicationMain.m
Reverts inverse-inc/sope#4
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803197 for details.
We might re-integrate this change later on, when libldap is fixed.
=> Revert "Close all file descriptors on daemon start"

configure
Previously the 'checkLinking <lib> optional' strings caused
trouble for distributions, because these checks are automagic, as in:
even if the user doesn't want ldap support, but ldap exists on the
system, it will still be used, possibly causing problems if
ldap is removed afterwards.
Making these things explicit fixes those problems. Default is
still automagic, unless --enable-\<feature\> or --disable-\<feature\>
is passed.
=> configure: allow more explicit control over dependencies

sope-core/NGExtensions/FdExt.subproj/NSSet+enumerator.m, sope-core/NGExtensions/FdExt.subproj/NSString+misc.m, sope-gdl1/GDLAccess/EOAdaptor.m, sope-gdl1/GDLAccess/EODatabaseFault.m, sope-gdl1/GDLAccess/EOSQLExpression.m, sope-gdl1/GDLAccess/EOSQLQualifier.m
Stage 5:
Missing header file imports. Some of these are needed to clear warnings in SOGo too.
=> Stage 5 of clang compiler warning patches. Missing header file imports.

sope-core/NGStreams/NGActiveSocket.m, sope-mime/NGMime/NGMimeRFC822DateHeaderFieldGenerator.m
1.) Cast NSLocale* to NSDictionary* when sending to [NSCalendarDate descriptionWithCalendarFormat]
2.) Add missing include of sys/types.h which causes a build error on FreeBSD.
=> Stage 7 of clang compiler warning patches.

sope-appserver/NGObjWeb/NSObject+WO.m, sope-appserver/NGObjWeb/SoObjects/SoSecurityException.h, sope-appserver/NGObjWeb/SoObjects/SoSecurityException.m, sope-appserver/NGObjWeb/SoObjects/SoSecurityManager.m, sope-appserver/NGObjWeb/SoObjects/common.h, sope-appserver/NGObjWeb/Templates/WOHTMLParser.m, sope-appserver/NGObjWeb/Templates/common.h, sope-appserver/NGObjWeb/common.h, sope-core/NGExtensions/FdExt.subproj/NGPropertyListParser.m, sope-core/NGExtensions/FdExt.subproj/NSException+misc.m, sope-core/NGExtensions/NGBundleManager.m, sope-core/NGExtensions/NGExtensions/NSException+misc.h, sope-gdl1/GDLAccess/EOFault.h, sope-gdl1/PostgreSQL/PostgreSQL72DataTypeMappingException.m, sope-gdl1/PostgreSQL/PostgreSQL72Values.h
Stage 9:
These fix build errors on FreeBSD and/or Clang and/or libobjc2.
They address the following issues:
(i) Runtime compatability logic in #if statements needs support for \_\_GNUSTEP_RUNTIME\_\_.
(ii) Fix build error by setting attribute for root class in EOFault.h.
(iii) Removed need for EXPOSE\_?\_IVARS in NGBundleManager.m by using isLoaded instead of \_codeLoaded.
(iv) Removed need for EXPOSE\_?\_IVARS in NSException+misc.h by removing the bad method 'setReason'. All uses of this method have been removed by setting the exceptions' 'reason' at init time, as it should be. An exceptions' 'reason' should be immutable, thus why there is no safe setter for it in NSException.
**Setting an ivar is not acceptable, and will be impossible in future versions of GNUstep Runtime.**
=> Stage 9 of clang compiler warning patches.

sope-gdl1/MySQL/GNUmakefile.preamble
Original patch by Russell Knighton <russell@annunaki2k2.co.uk>
Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=566138
Compilation fails with mysql:
```
x86_64-pc-linux-gnu-gcc NSCalendarDate+MySQL4Val.m -c \
-MMD -MP -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_GUI_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -m
arch=corei7-avx -O2 -pipe -fno-stack-protector -fgnu-runtime -fconstant-string-class=NSConstantString -I../GDLAccess -I.. -I../.. -I../../sope-core/ -I../../sope-core/NGExtensions -I. -I/va
r/tmp/portage/gnustep-libs/sope-2.3.2/work/GNUstep/Library/Headers -I/usr/local/include -I/usr/include \
-o obj/MySQL.obj/NSCalendarDate+MySQL4Val.m.o
In file included from /usr/include/mysql/mysql.h:64:0,
from …
```
=> Fix compilation with mysql

sope-gdl1/MySQL/MySQL4Channel.m
By default, SOGo connects to MySQL using the 'utf8' charset which maps to an incomplete Unicode implementation.  This change introduces the MySQL4Encoding configuration variable that can optionally be set to 'utf8mb4' to allow complete Unicode coverage; requires a properly configured MySQL >= 5.5 server.
=> Allow manual override of MySQL connection charset

configure, general.make
Also when possible, store GCC command-line switches
in the binaries for easier debugging.
Inspired by the way SOGo does it, using a general.make file.
=> Add -O2 compilation by default and -g debug info

configure
Prevent ./configure failure when run from a directory
such as "/home/bob/my own sope directory/"
=> Fix builds in directory names containing spaces

configure
Using /bin/sh instead does not cause any errors or issues in my usage on FreeBSD.
=> Convert 'configure' shebang back to /bin/sh for platform compatability

sope-mime/NGImap4/NSString+Imap4.m
(Fixes <https://sogo.nu/bugs/view.php?id=4308> and <https://sogo.nu/bugs/view.php?id=2318>, which has not been completely fixed. This applies to all versions of SOPE released from this Git repo from the very beginning of the history. Please merge it into all currently supported branches.)
According to https://tools.ietf.org/html/rfc3501#section-5.1.3 ,
in comparison to Base64 encoding, "," should be used instead of "/"
as the greatest digit of the base.
Of course, this meant that the encodings used by an IMAP server (e.g.,
dovecot) and SOGo did not match when they were communicating with each
other.
For example, when SOGo attempts to create a folder whose encoding
includes the base64 "/" digit, it is not accepted as valid mUTF7 by
the IMAP server:
C[0x5649de0d5d30]: 5 LIST "" "" …
=> correct mUTF7: 64th digit of the base is "," (RFC3501)

sope-json/SBJson/Classes/GNUmakefile
Because there is no GNUmakefile.preamble for sope-json/SBJson/Classes
libSBJson is not linked with BASE_LIBS (libgnustep-base an so on).
Our build system checks for undefined symbols in libraries and found
in libSBJson.so.2.3.1:
Verifying ELF objects in /usr/src/tmp/sope-buildroot (arch=normal,fhs=normal,lfs=relaxed,lint=relaxed,rpath=normal,stack=normal,textrel=normal,unresolved=normal)
verify-elf: ERROR: ./usr/lib64/libSBJson.so.2.3.1: undefined symbol: __objc_class_name_NSMutableArray
verify-elf: ERROR: ./usr/lib64/libSBJson.so.2.3.1: undefined symbol: __objc_class_name_NSDictionary
verify-elf: ERROR: ./usr/lib64/libSBJson.so.2.3.1: undefined symbol: __objc_class_name_NSError
verify-elf: ERROR: ./usr/lib64/libSBJson.so.2.3.1: undefined symbol: __objc_class_name_NSObject
verify-elf: …
=> Link libSBJson with BASE_LIBS to prevent undefined symbols

sope-appserver/NGObjWeb/Languages.plist
Fixes the error in SOGo, sogod : [ERROR] [we-rm] did not find locale for language: Chinese.
=> Add zh-cn and zh-tw to language list.

sope-mime/NGMail/NGSmtpClient.h, sope-mime/NGMail/NGSmtpClient.m
Add support for SMTPS and STARTTLS in smtpclient. Requires some changes in sogo to pass the scheme properly, see https://github.com/inverse-inc/sogo/pull/274
Fixes [#31](https://sogo.nu/bugs/view.php?id=31)
=> feat(smtp) Support SMTPS and STARTTLS

sope-xml/libxmlSAXDriver/libxmlHTMLSAXDriver.m
These functions must not be called with negative integers, except for EOF.
libxmlHTMLSAXDriver.m:784:9: error: array subscript is of type 'char' [-Werror,-Wchar-subscripts]
libxmlHTMLSAXDriver.m:797:49: error: array subscript is of type 'char' [-Werror,-Wchar-subscripts]
=> Fix usage of <ctype.h> functions

sope-appserver/NGObjWeb/WOHTTPConnection.m, sope-core/NGStreams/NGActiveSSLSocket.m, sope-core/NGStreams/NGStreams/NGActiveSSLSocket.h, sope-mime/NGImap4/NGImap4Client.m, sope-mime/NGImap4/NGSieveClient.m, sope-mime/NGMail/NGSmtpClient.m
Up to now, the peer certificates in TLS connections have not been verified after establishing the connection to the host. This is not very good practice, as it allows for man in the middle attacks even if the connection is being established.
Therefore, extend NGActiveSSLSocket to enable peer verification for OpenSSL and GnuTLS.
Both will reuse the default CA root trust store in order to verify the certificate.
As an addition, also send Server Name indications to the peer which allows the server we are connecting to to choose the right certificate.
Fixes [#5019](https://sogo.nu/bugs/view.php?id=5019)
=> feat(core): Peer verification on TLS connections

sope-appserver/NGObjWeb/WOHTTPConnection.m, sope-core/NGStreams/NGActiveSSLSocket.m, sope-core/NGStreams/NGStreams/NGActiveSSLSocket.h, sope-mime/NGImap4/NGImap4Client.m, sope-mime/NGImap4/NGSieveClient.m, sope-mime/NGMail/NGSmtpClient.m
Reverts inverse-inc/sope#52
This code causes too many issues on a lot of OSes:
/usr/share/GNUstep/Makefiles/rules.make:468: recipe for target 'obj/libNGStreams.obj/NGActiveSSLSocket.m.o' failed
make[6]: *** [obj/libNGStreams.obj/NGActiveSSLSocket.m.o] Error 1
/usr/share/GNUstep/Makefiles/Instance/library.make:275: recipe for target 'internal-library-all_' failed
make[5]: *** [internal-library-all_] Error 2
/usr/share/GNUstep/Makefiles/Master/rules.make:298: recipe for target 'libNGStreams.all.library.variables' failed
make[4]: *** [libNGStreams.all.library.variables] Error 2
/usr/share/GNUstep/Makefiles/Master/library.make:37: recipe for target 'internal-all' failed
make[3]: *** [internal-all] Error 2
make[3]: Leaving directory '/root/src/sope-4.9/sope-core/NGStreams' …
=> Revert "feat(core): Peer verification on TLS connections"

sope-mime/NGMime/NGMimeHeaderFieldGenerator.m
The lookup table in NGMimeHeaderFieldGenerator.m is much more restrictive than the defintion of printable characters in https://tools.ietf.org/html/rfc2047#section-4.2.
We have issues answering messages from JIRA as the identification tag in the subject-header `(LNRWS-123)` is currently being escaped to `=?utf-8?q?=28LNRWS-122=29?=`. (I know that it's actually on JIRA to decode the header correctly before parsing, but there's nothing we could do in this case).
I completely removed the lookup table as there are only three excluded characters left.
=> Fixed set of printable characters in quoted printable according to RFC2047

sope-appserver/NGObjWeb/WOHTTPConnection.m, sope-core/NGExtensions/FdExt.subproj/NSURL+misc.m, sope-core/NGExtensions/NGExtensions/NSURL+misc.h, sope-core/NGStreams/NGActiveSSLSocket.m, sope-core/NGStreams/NGInternetSocketAddress.m, sope-core/NGStreams/NGLocalSocketAddress.m, sope-core/NGStreams/NGStreams/NGActiveSSLSocket.h, sope-core/NGStreams/NGStreams/NGInternetSocketAddress.h, sope-core/NGStreams/NGStreams/NGSocketProtocols.h, sope-mime/NGImap4/NGImap4Client.h, sope-mime/NGImap4/NGImap4Client.m, sope-mime/NGImap4/NGSieveClient.h, sope-mime/NGImap4/NGSieveClient.m, sope-mime/NGMail/NGSmtpClient.h, sope-mime/NGMail/NGSmtpClient.m, sope-mime/NGMime/NGMimeType.m
Add options to SMTP, IMAP, and Sieve clients disable TLS validation for localhost or completely.
To simplify the handling the the query itself, extend NSURL with a category extension implementing `queryComponents` allowing for getting the query key/value pairs from a NSDictionary.
Also rewrite the handling of starttls, now NGActiveSSLSocket can take over getting the socket file descriptor and setting up the socket properly.
Refs [#5078](https://sogo.nu/bugs/view.php?id=5078)
=> feat(core): Implement optional TLS validation

sope-appserver/NGObjWeb/WORequest.m
Free the memory allocated by calloc() again by passing `freeWhenDone: YES`
=> fix(appserver): Fix memory leak

sope-appserver/NGObjWeb/WORequest.m, sope-core/NGStreams/NGActiveSSLSocket.m, sope-core/NGStreams/NGActiveSocket.m, sope-core/NGStreams/NGSocket.m, sope-core/NGStreams/NGStreams/NGSocket.h
When STARTTLS is used, we re-use the connection and put a
new socket "on top" of the old one and reuse the file
descriptor of the previous socket.
This lead to two issues: First, now both sockets tried to close
the underlying file descriptor: Once from the non-starttls connection,
once by the starttls connection. This wasnt so harmful, as closing would
fail with EBADF. Fix this by using the flag `closeOnFree` for such
fd assignments, in this way the ownership is clearer.
The second issue is more severe: when passing the fd to the TLS socket,
the TLS socket could already have an fd assigned, but that would never
be freed. To fix the fd leak simply call `close` on the old fd
when `setFileDescriptor` is called.
Fixes: [#5175](https://sogo.nu/bugs/view.php?id=5175)
=> fix(core): Dont leak fd when using STARTTLS

configure
Things like `NIX_GNUSTEP_BASE` would get pulled in without this patch which causes the build to fail.
=> fix(configure): Prevent pulling in unnecessary vars

sope-mime/NGMail/NGSmtpClient.m
Rather than treating the SMTP output as a format string, explicitly specify a format string. This is more secure and allows building with `-Wformat -Wformat-security -Werror=format-security`
=> fix(smtp): Fix -Wformat

sope-mime/NGMime/NGMimeType.m
some enum constants in gnustep base libs have changed with 1.29.0, which breaks compatibility with sope.
changing commit is: https://github.com/gnustep/libs-base/commit/fe2f41c7f19f19bf8b5100a2124e815d92d784d1
only two enum constants in NGMimeType.m are affected, both of which under a section commented with "some unsupported, but known encoding". from gnustep base 1.29.0 on there are multiple enum constants for GB2312 encoding. after some research i decided to go for NSHZ_GB_2312StringEncoding, because it references the 7-bit HZ-encoding used in mailing.
=> support for gnustep base >= 1.29.0

sope-appserver/NGObjWeb/SoObjects/SoDefaultRenderer.m
Currently DAV errors have incorrect namespace of _error_ tag "DAV" but it should "DAV:" with a colon.
Example of error I get:
HTTP/1.1 403 Forbidden
```
content-length: 93
content-type: application/xml; charset="utf-8"
<?xml version="1.0" encoding="utf-8"?>
<D:error xmlns:D="DAV">sequences don't match</D:error>
```
RFC https://datatracker.ietf.org/doc/html/rfc4918#section-14 in section 14 says that "All elements defined here are in the "DAV:" namespace."
Section 14.5 describes the error element.
All examples of using _error_ element are desribed as
```xml
<D:error xmlns:D="DAV:">
...
</D:error>
```
This PR changes the namespace from DAV to DAV:
SOGo BTS: https://bugs.sogo.nu/view.php?id=5964
=> Fix XML namespace for DAV error element

sope-core/NGExtensions/NGHashMap.m
Hello,
I found a DoS bug in SOPE.
It is way too easy to trigger with curl:
curl -d 'x=' 'https://.../SOGo/?x='
As far as I can tell all versions since SOGo-2.0.2 (2012-10-29) are affected.
I found it inspecting multiple SOGo crashes triggered by someone hitting URLs like `/OA_HTML/BneViewerXMLService?bne:uueupload=TRUE` with `POST` that my search engine associates with "Oracle E-Business Suite (EBS)".
The crash happens in NGHashMap.m line 790, as root->last is NULL: https://github.com/Alinto/sope/blob/3146fbdb6ff3314e37e5c3682deeeef7d0f32064/sope-core/NGExtensions/NGHashMap.m#L790
NGHashMap maps a key to a single-linked list of values.
It turns out `-[NGMutableHashMap addObjects:count:forKey:]` is the only function maintaining the `root->last` pointer; everything else in this file doesn't …
=> fix DoS segfault (NULL pointer deref) in SOPE / SOGo
